### listAll Libros
GET http://localhost:8082/libros

### Save Libro
POST http://localhost:8082/libros
Content-Type: application/json

{
  "idLibro": 22,
  "name": "test",
  "author": "test",
  "editorial": "test",
  "numPages": 342,
  "disponible": true,
  "idUser": 10
}

### Update Libro
PUT http://localhost:8082/libros/22
Content-Type: application/json

{
  "idLibro": 22,
  "name": "testUpdate",
  "author": "testUpdate",
  "editorial": "testUpdate",
  "numPages": 342,
  "disponible": true,
  "idUser": 10
}

### List By ID
GET http://localhost:8082/libros/22
Content-Type: application/json

{
  "idLibro": 22
}

### Delete Libro
DELETE http://localhost:8082/libros/22
Content-Type: application/json

{
  "idLibro": 22
}