### List All Users
GET http://localhost:8082/user

### Save User
POST http://localhost:8082/user
Content-Type: application/json

{
  "idUser": 12,
  "name": "test",
  "nif": "test"
}

### List User By Id
GET http://localhost:8082/user/11
Content-Type: application/json

{
  "idUser": 11
}



### Update User By Id
PUT http://localhost:8082/user/12
Content-Type: application/json

{
  "idUser": 12,
  "name": "testUpdate",
  "nif": "testUpdate"
}

### Delete User By Id
DELETE http://localhost:8082/user/12
Content-Type: application/json

{
  "idUser": 12
}